<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Articles.aspx.cs" Inherits="WebApplication7.Articles" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" DataSourceID="SqlDataSource1" ForeColor="Black" GridLines="None" >
            <AlternatingRowStyle BackColor="PaleGoldenrod" />
            <Columns>
                 <asp:TemplateField HeaderText="Select">
                    <ItemTemplate>
                        <asp:CheckBox runat="server" ID="chkSelect"/>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="ArticleID" HeaderText="ArticleID" InsertVisible="False" ReadOnly="True" SortExpression="ArticleID" />
                <asp:BoundField DataField="ArticleTitle" HeaderText="ArticleTitle" SortExpression="ArticleTitle" />
                <asp:BoundField DataField="ArticleText" HeaderText="ArticleText" SortExpression="ArticleText" />
               <asp:TemplateField HeaderText="to shopping cart?">
                   <ItemTemplate>
                       <%#
    this.Eval("ArticleID").ToString().Equals("True")?"Yes":"No" %>
                   </ItemTemplate>
               </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="Tan" />
            <HeaderStyle BackColor="Tan" Font-Bold="True" />
            <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
            <SortedAscendingCellStyle BackColor="#FAFAE7" />
            <SortedAscendingHeaderStyle BackColor="#DAC09E" />
            <SortedDescendingCellStyle BackColor="#E1DB9C" />
            <SortedDescendingHeaderStyle BackColor="#C2A47B" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:FlexBricksTestConnectionString %>" SelectCommand="SELECT * FROM [ARTICLES]" ConflictDetection="CompareAllValues" InsertCommand="INSERT INTO [ARTICLES] ([ArticleTitle], [ArticleText]) VALUES (@ArticleTitle, @ArticleText)" OldValuesParameterFormatString="original_{0}" >
            <InsertParameters>
                <asp:Parameter Name="ArticleTitle" Type="String" />
                <asp:Parameter Name="ArticleText" Type="String" />
            </InsertParameters>
        </asp:SqlDataSource>
        <br />
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
        <asp:Button ID="Button1" runat="server" Text="Add new item" OnClick="Button1_Click" />
        <asp:Button ID="Button2" runat="server" Text="Order items" OnClick="GetSelectedRecords" />
    </div>
    </form>
</body>
</html>
